name: GuglLens
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - faiss-cpu
  - torchvision
  - pytorch
  - pyside6
  - sqlmodel
  - tqdm
  - opencv
  - pytest
  - bokeh
  - panel
  - holoviews
  - datashader
